/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bbeasley' at '1/25/17 11:03 AM' with Gradle 2.4
 *
 * @author bbeasley, @date 1/25/17 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
